### ISSUE TITLE
페이지 내용을 바꾸었으나 읽기 모드에선 수정전 내용이 보임

### ISSUE THREAD

**Issue by 0hoo** [akngs/ecogwiki#33]
/sp.flush_cache 하면 괜찮음

**Comment by akngs** [comment]
혹시 이것도 어제 작업했던 cache 문제랑 같은 것일지 모르겠다는 느낌이 드는데!?

**Comment by 0hoo** [comment]
그럴거 같음. 일단 닫고 다시 보이면 생성해도 됨.

**Comment by jangxyz** [comment]
전 자주 이래서 그냥 조용히 sp.cache_flush 해왔는데.. 이제 해결 된건가요? +_+

2014년 1월 9일 목요일에 0hoo님이 작성:

**Comment by akngs** [comment]
아예 instance cache를 제거하고 예전에 쓰던 per-request cache (threadlocal cache) 를 다시 넣었습니다. 이제 이 문제는 안나타날듯.
