### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by akngs** [akngs/ecogwiki#48]

**Comment by akngs** [comment]
See [Blobstore API with GCS](https://developers.google.com/appengine/docs/python/blobstore/#Python_Using_the_Blobstore_API_with_Google_Cloud_Storage)

**Comment by jangxyz** [comment]
+1

Additionally, if it's ok to let user upload to their own google drive,
check Google Picker (
http://googleappsdeveloper.blogspot.kr/2012/06/using-google-picker-to-upload-files-to.html
 )

2014년 1월 10일 금요일에 Alan Kang님이 작성:

**Comment by akngs** [comment]
I am actually considering Google Drive, but sadly, Google Picker doesn't support mobile browsers yet. Think I have to use oauth or something.

**Comment by jangxyz** [comment]
I think Google Picker does use OAuth already. I'm curious whether 'the usage of Google Drive' is to upload on each users' own drives, or to the server's. I thought the Blobstore API was to save the images on server side.

Is the only objection for Google Picker the one with mobile browsers?

**Comment by akngs** [comment]
At first I was considering the Blobstore API as the only storage backend, but now I think there could be more than one storage. Google Drive fits better for the current situation. By the current situation, I mean the project sponsor's requirements ;-)

And yes, the lack of mobile browser support is the only obstacle so far. Except for that, it looks really great.

**Comment by jangxyz** [comment]
Great. Maybe I could try a spike implementation, hoping someone might come up with mobile.

Let me just mention that there exist at least one person who prefers Dropbox as their personal backend to Google Drive ;)

**Comment by akngs** [comment]
:+1:

**Comment by akngs** [comment]
I'm working on it now. See 424bcb7b41cb881851312cb73a1a7092b6f58315
