### ISSUE TITLE
_가 들어간 URL을 파싱하지 못하는 문제가 있는것으로 보입니다. 

### ISSUE THREAD

**Issue by caesar13** [akngs/ecogwiki#66]
에디터에서 http://blogs.msdn.com/b/david_gristwood/archive/2004/06/24/164849.aspx 링크를 추가하려고 했는데 _이후의 텍스트가 italic으로 표시되고 이 텍스트가 있는 페이지를 Save하려고 하면  

<pre>
Cannot accept the data for following reasons:
Duplicate paths not allowed
</pre>

라는 메시지가 나오면서 save가 되지 않습니다.

**Comment by akngs** [comment]
"Duplicated paths not allowed"는 동일한 제목이 두 개 이상 있어서 나오는 오류입니다. 그런 부분이 있는지 한 번 확인해보시겠어요?

**Comment by caesar13** [comment]
제목 쓸 때 # 를 쓰지 않고 ##를 사용해서 생긴 문제였습니다. 빠른 답변 감사드립니다.
