### ISSUE TITLE
h2부터 사용할 시 오류가 발생하는 문제

### ISSUE THREAD

**Issue by clockoon** [akngs/ecogwiki#69]
본문에 heading을 줄 때 h1를 사용하지 않고 h2부터 사용하였을 경우에 _Duplicate paths not allowed_ 에러가 발생합니다.

**Comment by akngs** [comment]
heading을 순서대로 쓰게 하기 위해 넣은 제약입니다. 근데 오류 메시지가 "Duplicated paths ..."라고 나오는건 바꿔야겠네요 ^^;;

**Comment by clockoon** [comment]
본문에 h1을 안 쓰는 경우에도(h2 먼저 쓰고 h1 쓰는 게 아니라) 작동 가능했으면 좋겠습니다. 보통 제목에만 h1을 쓰니까요..

**Comment by akngs** [comment]
section element 안의 top level에 h1이 여러개 나오는건 괜찮답니다. 혹시 글자 크기 때문이라면 css를 변경하시면 더 좋을 것 같아요.
