### ISSUE TITLE
다중속성을 가진 schema property의 json 인코딩 문제

### ISSUE THREAD

**Issue by jangxyz** [akngs/ecogwiki#84]
여러개의 값을 가지는 schema property를 배열 형태로 선언할 수 있는데, 이것이 json 인코딩 시 문제를 일으킵니다.

예:

```
author: ["강규영", "김장환"]
```

로그를 보면 `schema.ThingProperty`을 JSON이 serialize 시키려다 실패한다고 나옵니다.

```
ERROR    2014-02-08 07:45:49,961 webapp2.py:1528] <schema.ThingProperty object at 0x10709c750> is not JSON serializable
```

[예시 페이지](http://www.ecogwiki.com/%ED%8F%AD%ED%83%84/nested_object%EC%9D%98_json_%EB%AC%B8%EC%A0%9C)에서 에러를 확인해볼 수 있습니다.

**Comment by akngs** [comment]
폭탄 테러리스트 ㅋㅋ (고맙습니다 ㅎ)

**Comment by akngs** [comment]
고쳤어요~

**Comment by jangxyz** [comment]
저.. 예시 페이지는 계속 깨지는데... www.ecogwiki.com 은 항상 master인게 아니었나요?

**Comment by akngs** [comment]
배포는 아직. push는 했으니 보시라능~
